# Problem 45: Triangular, pentagonal, and hexagonal
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
# Find the next triangle number that is also pentagonal and hexagonal.
def tri(n):
  return n*(n+1)//2
def pen(n):
  return n*(3*n-1)//2
def hex(n):
  return n*(2*n-1)

nt,np,nh = 286,165,143
t,p,h = tri(nt),pen(np),hex(nh)
while t!=p or t!=h:
  while t<p or t<h:
    nt += 1
    t = tri(nt)
  while p<t:
    np += 1
    p = pen(np)
  while h<t:
    nh += 1
    h = hex(nh)
print(t)
  
  