# Problem 12: Highest divisible triangular number
# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten # terms would be:
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# Let us list the factors of the first seven triangle numbers:
# 1: 1
# 3: 1,3
# 6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.
# What is the value of the first triangle number to have over five hundred divisors?
N = 500
target = 500
import numpy as np
import math
while True:
  N += 1
  tri = N*(N+1)//2
  maxval = int(math.ceil(tri**0.5))
  v = np.array(range(1,maxval+1))
  numdiv = 2*np.count_nonzero(tri%v==0)
  if numdiv > target:
    print(tri)
    break
  